services:
  pokemonlookup:
    image: pokemonlookup
    build:
      context: .
      dockerfile: PokemonLookup.Web/Dockerfile
    depends_on:
      - postgres
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_DB: ${DATABASE_DB}
  postgres:
    image: postgres:latest
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_DB}
