# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'zulu' # Alternative distribution options are available.
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore PokemonLookup/PokemonLookup.sln
    - name: Setup Code Coverage
      run: |
        sudo apt-get update && sudo apt-get install glibc-source libxml2 libxrender1 libfontconfig libxext6 libc6 -y
        dotnet tool install --global dotnet-coverage
    - name: Sonarqube Begin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: | 
        dotnet tool install --global dotnet-sonarscanner
        dotnet sonarscanner begin /k:"laternenpolster_sqs-vorlesung" /o:"laternenpolster" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
    - name: Build
      run: dotnet build --no-restore --no-incremental PokemonLookup/PokemonLookup.sln
    - name: Code Formatting
      run: dotnet format --verify-no-changes PokemonLookup
    - name: Ensure browsers are installed
      run: pwsh PokemonLookup/PokemonLookup.End2EndTests/bin/Debug/net8.0/playwright.ps1 install --with-deps
    - name: Unit Test
      run: dotnet test --no-build --verbosity normal PokemonLookup/PokemonLookup.UnitTests/PokemonLookup.UnitTests.csproj
    - name: Architecture Test
      run: dotnet test --no-build --verbosity normal PokemonLookup/PokemonLookup.ArchitectureTests/PokemonLookup.ArchitectureTests.csproj 
    - name: Integration Test
      run: dotnet test --no-build --verbosity normal PokemonLookup/PokemonLookup.IntegrationTests/PokemonLookup.IntegrationTests.csproj
    - name: End2End Test
      run: dotnet test --no-build --verbosity normal PokemonLookup/PokemonLookup.End2EndTests/PokemonLookup.End2EndTests.csproj
    - name: Load Test
      run: dotnet test --no-build --verbosity normal PokemonLookup/PokemonLookup.LoadTests/PokemonLookup.LoadTests.csproj
    - name: Coverage
      run: dotnet-coverage collect "dotnet test PokemonLookup/PokemonLookup.sln" -f xml -o "coverage.xml"
    - name: Sonarqube end
      run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
